// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: protobuf/arthas.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义动作枚举
type Action int32

const (
	Action_LOGIN               Action = 0
	Action_LOGOUT              Action = 1
	Action_SEND_MESSAGE        Action = 2
	Action_SEND_GROUP_MESSAGE  Action = 3
	Action_SYNC_ACCOUNT_KEY    Action = 4 // 添加同步帐号密钥动作
	Action_GET_PREKEYBUNDLE    Action = 5
	Action_SYNC_CONTACTS       Action = 6
	Action_PING_PONG           Action = 7
	Action_SEND_VCARD_MESSAGE  Action = 8
	Action_SET_HEAD_SCULPTURE  Action = 9
	Action_GET_USER_HEAD_IMAGE Action = 10
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "LOGIN",
		1:  "LOGOUT",
		2:  "SEND_MESSAGE",
		3:  "SEND_GROUP_MESSAGE",
		4:  "SYNC_ACCOUNT_KEY",
		5:  "GET_PREKEYBUNDLE",
		6:  "SYNC_CONTACTS",
		7:  "PING_PONG",
		8:  "SEND_VCARD_MESSAGE",
		9:  "SET_HEAD_SCULPTURE",
		10: "GET_USER_HEAD_IMAGE",
	}
	Action_value = map[string]int32{
		"LOGIN":               0,
		"LOGOUT":              1,
		"SEND_MESSAGE":        2,
		"SEND_GROUP_MESSAGE":  3,
		"SYNC_ACCOUNT_KEY":    4,
		"GET_PREKEYBUNDLE":    5,
		"SYNC_CONTACTS":       6,
		"PING_PONG":           7,
		"SEND_VCARD_MESSAGE":  8,
		"SET_HEAD_SCULPTURE":  9,
		"GET_USER_HEAD_IMAGE": 10,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_arthas_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_protobuf_arthas_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{0}
}

// 定义动作的返回状态枚举
type ActionResult int32

const (
	ActionResult_ALL_SUCCESS     ActionResult = 0
	ActionResult_PARTIAL_SUCCESS ActionResult = 1
	ActionResult_ALL_FAIL        ActionResult = 2
	ActionResult_ALL_UNKNOWN     ActionResult = 3
	ActionResult_PONG            ActionResult = 4
)

// Enum value maps for ActionResult.
var (
	ActionResult_name = map[int32]string{
		0: "ALL_SUCCESS",
		1: "PARTIAL_SUCCESS",
		2: "ALL_FAIL",
		3: "ALL_UNKNOWN",
		4: "PONG",
	}
	ActionResult_value = map[string]int32{
		"ALL_SUCCESS":     0,
		"PARTIAL_SUCCESS": 1,
		"ALL_FAIL":        2,
		"ALL_UNKNOWN":     3,
		"PONG":            4,
	}
)

func (x ActionResult) Enum() *ActionResult {
	p := new(ActionResult)
	*p = x
	return p
}

func (x ActionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_arthas_proto_enumTypes[1].Descriptor()
}

func (ActionResult) Type() protoreflect.EnumType {
	return &file_protobuf_arthas_proto_enumTypes[1]
}

func (x ActionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionResult.Descriptor instead.
func (ActionResult) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{1}
}

// 定义单个帐号的执行状态枚举
type AccountStatus int32

const (
	AccountStatus_SUCCESS    AccountStatus = 0   //成功
	AccountStatus_FAIL       AccountStatus = 1   //失败
	AccountStatus_UNKNOWN    AccountStatus = 2   //未知
	AccountStatus_NOT_EXIST  AccountStatus = 3   //账号不存在
	AccountStatus_SEAL       AccountStatus = 403 //登录失败，已封号
	AccountStatus_PERMISSION AccountStatus = 401 // 登录失败，权限错误
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0:   "SUCCESS",
		1:   "FAIL",
		2:   "UNKNOWN",
		3:   "NOT_EXIST",
		403: "SEAL",
		401: "PERMISSION",
	}
	AccountStatus_value = map[string]int32{
		"SUCCESS":    0,
		"FAIL":       1,
		"UNKNOWN":    2,
		"NOT_EXIST":  3,
		"SEAL":       403,
		"PERMISSION": 401,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_arthas_proto_enumTypes[2].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_protobuf_arthas_proto_enumTypes[2]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{2}
}

type OrdinaryAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginDetail map[uint64]*LoginDetail `protobuf:"bytes,1,rep,name=login_detail,json=loginDetail,proto3" json:"login_detail,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OrdinaryAction) Reset() {
	*x = OrdinaryAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdinaryAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdinaryAction) ProtoMessage() {}

func (x *OrdinaryAction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdinaryAction.ProtoReflect.Descriptor instead.
func (*OrdinaryAction) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{0}
}

func (x *OrdinaryAction) GetLoginDetail() map[uint64]*LoginDetail {
	if x != nil {
		return x.LoginDetail
	}
	return nil
}

type LoginDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyUrl string `protobuf:"bytes,1,opt,name=proxyUrl,proto3" json:"proxyUrl,omitempty"`
}

func (x *LoginDetail) Reset() {
	*x = LoginDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDetail) ProtoMessage() {}

func (x *LoginDetail) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginDetail.ProtoReflect.Descriptor instead.
func (*LoginDetail) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{1}
}

func (x *LoginDetail) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

type GetUserHeadImageAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account uint64 `protobuf:"varint,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *GetUserHeadImageAction) Reset() {
	*x = GetUserHeadImageAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserHeadImageAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHeadImageAction) ProtoMessage() {}

func (x *GetUserHeadImageAction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHeadImageAction.ProtoReflect.Descriptor instead.
func (*GetUserHeadImageAction) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserHeadImageAction) GetAccount() uint64 {
	if x != nil {
		return x.Account
	}
	return 0
}

// 定义头像
type HeadSculpture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image   []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Account uint64 `protobuf:"varint,2,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *HeadSculpture) Reset() {
	*x = HeadSculpture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadSculpture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadSculpture) ProtoMessage() {}

func (x *HeadSculpture) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadSculpture.ProtoReflect.Descriptor instead.
func (*HeadSculpture) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{3}
}

func (x *HeadSculpture) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *HeadSculpture) GetAccount() uint64 {
	if x != nil {
		return x.Account
	}
	return 0
}

// 修改头像信息
type SetHeadSculptureAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadSculptrueData *HeadSculpture `protobuf:"bytes,1,opt,name=HeadSculptrue_data,json=HeadSculptrueData,proto3" json:"HeadSculptrue_data,omitempty"`
}

func (x *SetHeadSculptureAction) Reset() {
	*x = SetHeadSculptureAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetHeadSculptureAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeadSculptureAction) ProtoMessage() {}

func (x *SetHeadSculptureAction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeadSculptureAction.ProtoReflect.Descriptor instead.
func (*SetHeadSculptureAction) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{4}
}

func (x *SetHeadSculptureAction) GetHeadSculptrueData() *HeadSculpture {
	if x != nil {
		return x.HeadSculptrueData
	}
	return nil
}

// 定义明信片
type VCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Begin       string `protobuf:"bytes,1,opt,name=Begin,proto3" json:"Begin,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Prodid      string `protobuf:"bytes,3,opt,name=Prodid,proto3" json:"Prodid,omitempty"`
	Fn          string `protobuf:"bytes,4,opt,name=Fn,proto3" json:"Fn,omitempty"`
	Org         string `protobuf:"bytes,5,opt,name=Org,proto3" json:"Org,omitempty"`
	Tel         string `protobuf:"bytes,6,opt,name=Tel,proto3" json:"Tel,omitempty"`
	XWaBizName  string `protobuf:"bytes,7,opt,name=XWaBizName,proto3" json:"XWaBizName,omitempty"`
	End         string `protobuf:"bytes,9,opt,name=End,proto3" json:"End,omitempty"`
	DisplayName string `protobuf:"bytes,10,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Family      string `protobuf:"bytes,11,opt,name=Family,proto3" json:"Family,omitempty"`
	Given       string `protobuf:"bytes,12,opt,name=Given,proto3" json:"Given,omitempty"`
	Prefixes    string `protobuf:"bytes,13,opt,name=Prefixes,proto3" json:"Prefixes,omitempty"`
	Language    string `protobuf:"bytes,14,opt,name=Language,proto3" json:"Language,omitempty"`
}

func (x *VCard) Reset() {
	*x = VCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCard) ProtoMessage() {}

func (x *VCard) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCard.ProtoReflect.Descriptor instead.
func (*VCard) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{5}
}

func (x *VCard) GetBegin() string {
	if x != nil {
		return x.Begin
	}
	return ""
}

func (x *VCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VCard) GetProdid() string {
	if x != nil {
		return x.Prodid
	}
	return ""
}

func (x *VCard) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *VCard) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *VCard) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *VCard) GetXWaBizName() string {
	if x != nil {
		return x.XWaBizName
	}
	return ""
}

func (x *VCard) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *VCard) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *VCard) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *VCard) GetGiven() string {
	if x != nil {
		return x.Given
	}
	return ""
}

func (x *VCard) GetPrefixes() string {
	if x != nil {
		return x.Prefixes
	}
	return ""
}

func (x *VCard) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// 定义明信片消息
type SendVCardMsgAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VcardData map[uint64]*VCard `protobuf:"bytes,1,rep,name=Vcard_data,json=VcardData,proto3" json:"Vcard_data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sender    uint64            `protobuf:"varint,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver  uint64            `protobuf:"varint,3,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
}

func (x *SendVCardMsgAction) Reset() {
	*x = SendVCardMsgAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVCardMsgAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVCardMsgAction) ProtoMessage() {}

func (x *SendVCardMsgAction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVCardMsgAction.ProtoReflect.Descriptor instead.
func (*SendVCardMsgAction) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{6}
}

func (x *SendVCardMsgAction) GetVcardData() map[uint64]*VCard {
	if x != nil {
		return x.VcardData
	}
	return nil
}

func (x *SendVCardMsgAction) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *SendVCardMsgAction) GetReceiver() uint64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

// 定义密钥数据
type KeyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Privatekey       []byte `protobuf:"bytes,1,opt,name=privatekey,proto3" json:"privatekey,omitempty"`
	PrivateMsgKey    []byte `protobuf:"bytes,2,opt,name=privateMsgKey,proto3" json:"privateMsgKey,omitempty"`
	ResumptionSecret []byte `protobuf:"bytes,3,opt,name=resumptionSecret,proto3" json:"resumptionSecret,omitempty"`
	Publickey        []byte `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
	PublicMsgKey     []byte `protobuf:"bytes,5,opt,name=publicMsgKey,proto3" json:"publicMsgKey,omitempty"`
	ClientPayload    []byte `protobuf:"bytes,6,opt,name=clientPayload,proto3" json:"clientPayload,omitempty"`
	Identify         []byte `protobuf:"bytes,7,opt,name=identify,proto3" json:"identify,omitempty"`
}

func (x *KeyData) Reset() {
	*x = KeyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyData) ProtoMessage() {}

func (x *KeyData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyData.ProtoReflect.Descriptor instead.
func (*KeyData) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{7}
}

func (x *KeyData) GetPrivatekey() []byte {
	if x != nil {
		return x.Privatekey
	}
	return nil
}

func (x *KeyData) GetPrivateMsgKey() []byte {
	if x != nil {
		return x.PrivateMsgKey
	}
	return nil
}

func (x *KeyData) GetResumptionSecret() []byte {
	if x != nil {
		return x.ResumptionSecret
	}
	return nil
}

func (x *KeyData) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *KeyData) GetPublicMsgKey() []byte {
	if x != nil {
		return x.PublicMsgKey
	}
	return nil
}

func (x *KeyData) GetClientPayload() []byte {
	if x != nil {
		return x.ClientPayload
	}
	return nil
}

func (x *KeyData) GetIdentify() []byte {
	if x != nil {
		return x.Identify
	}
	return nil
}

// 定义同步帐号密钥动作消息
type SyncAccountKeyAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyData map[uint64]*KeyData `protobuf:"bytes,1,rep,name=key_data,json=keyData,proto3" json:"key_data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SyncAccountKeyAction) Reset() {
	*x = SyncAccountKeyAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAccountKeyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAccountKeyAction) ProtoMessage() {}

func (x *SyncAccountKeyAction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAccountKeyAction.ProtoReflect.Descriptor instead.
func (*SyncAccountKeyAction) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{8}
}

func (x *SyncAccountKeyAction) GetKeyData() map[uint64]*KeyData {
	if x != nil {
		return x.KeyData
	}
	return nil
}

// 定义总的消息
type RequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Action `protobuf:"varint,1,opt,name=action,proto3,enum=Action" json:"action,omitempty"` // 动作字段
	// Types that are assignable to ActionDetail:
	//
	//	*RequestMessage_OrdinaryAction
	//	*RequestMessage_SyncAccountKeyAction
	//	*RequestMessage_QueryPrekeybundleDetail
	//	*RequestMessage_SendmessageDetail
	//	*RequestMessage_PingMessage
	//	*RequestMessage_SendVcardMessage
	//	*RequestMessage_SetHeadSculptureAction
	//	*RequestMessage_GetUserHeadImage
	ActionDetail isRequestMessage_ActionDetail `protobuf_oneof:"action_detail"`
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{9}
}

func (x *RequestMessage) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_LOGIN
}

func (m *RequestMessage) GetActionDetail() isRequestMessage_ActionDetail {
	if m != nil {
		return m.ActionDetail
	}
	return nil
}

func (x *RequestMessage) GetOrdinaryAction() *OrdinaryAction {
	if x, ok := x.GetActionDetail().(*RequestMessage_OrdinaryAction); ok {
		return x.OrdinaryAction
	}
	return nil
}

func (x *RequestMessage) GetSyncAccountKeyAction() *SyncAccountKeyAction {
	if x, ok := x.GetActionDetail().(*RequestMessage_SyncAccountKeyAction); ok {
		return x.SyncAccountKeyAction
	}
	return nil
}

func (x *RequestMessage) GetQueryPrekeybundleDetail() *QueryPreKeyBundleDetail {
	if x, ok := x.GetActionDetail().(*RequestMessage_QueryPrekeybundleDetail); ok {
		return x.QueryPrekeybundleDetail
	}
	return nil
}

func (x *RequestMessage) GetSendmessageDetail() *SendMessageDetail {
	if x, ok := x.GetActionDetail().(*RequestMessage_SendmessageDetail); ok {
		return x.SendmessageDetail
	}
	return nil
}

func (x *RequestMessage) GetPingMessage() string {
	if x, ok := x.GetActionDetail().(*RequestMessage_PingMessage); ok {
		return x.PingMessage
	}
	return ""
}

func (x *RequestMessage) GetSendVcardMessage() *SendVCardMsgAction {
	if x, ok := x.GetActionDetail().(*RequestMessage_SendVcardMessage); ok {
		return x.SendVcardMessage
	}
	return nil
}

func (x *RequestMessage) GetSetHeadSculptureAction() *SetHeadSculptureAction {
	if x, ok := x.GetActionDetail().(*RequestMessage_SetHeadSculptureAction); ok {
		return x.SetHeadSculptureAction
	}
	return nil
}

func (x *RequestMessage) GetGetUserHeadImage() *GetUserHeadImageAction {
	if x, ok := x.GetActionDetail().(*RequestMessage_GetUserHeadImage); ok {
		return x.GetUserHeadImage
	}
	return nil
}

type isRequestMessage_ActionDetail interface {
	isRequestMessage_ActionDetail()
}

type RequestMessage_OrdinaryAction struct {
	OrdinaryAction *OrdinaryAction `protobuf:"bytes,2,opt,name=ordinary_action,json=ordinaryAction,proto3,oneof"`
}

type RequestMessage_SyncAccountKeyAction struct {
	SyncAccountKeyAction *SyncAccountKeyAction `protobuf:"bytes,3,opt,name=sync_account_key_action,json=syncAccountKeyAction,proto3,oneof"`
}

type RequestMessage_QueryPrekeybundleDetail struct {
	QueryPrekeybundleDetail *QueryPreKeyBundleDetail `protobuf:"bytes,7,opt,name=query_prekeybundle_detail,json=queryPrekeybundleDetail,proto3,oneof"`
}

type RequestMessage_SendmessageDetail struct {
	SendmessageDetail *SendMessageDetail `protobuf:"bytes,8,opt,name=sendmessage_detail,json=sendmessageDetail,proto3,oneof"`
}

type RequestMessage_PingMessage struct {
	PingMessage string `protobuf:"bytes,9,opt,name=ping_message,json=pingMessage,proto3,oneof"`
}

type RequestMessage_SendVcardMessage struct {
	SendVcardMessage *SendVCardMsgAction `protobuf:"bytes,10,opt,name=send_vcard_message,json=sendVcardMessage,proto3,oneof"`
}

type RequestMessage_SetHeadSculptureAction struct {
	SetHeadSculptureAction *SetHeadSculptureAction `protobuf:"bytes,11,opt,name=set_head_sculpture_action,json=setHeadSculptureAction,proto3,oneof"`
}

type RequestMessage_GetUserHeadImage struct {
	GetUserHeadImage *GetUserHeadImageAction `protobuf:"bytes,12,opt,name=get_user_head_image,json=getUserHeadImage,proto3,oneof"`
}

func (*RequestMessage_OrdinaryAction) isRequestMessage_ActionDetail() {}

func (*RequestMessage_SyncAccountKeyAction) isRequestMessage_ActionDetail() {}

func (*RequestMessage_QueryPrekeybundleDetail) isRequestMessage_ActionDetail() {}

func (*RequestMessage_SendmessageDetail) isRequestMessage_ActionDetail() {}

func (*RequestMessage_PingMessage) isRequestMessage_ActionDetail() {}

func (*RequestMessage_SendVcardMessage) isRequestMessage_ActionDetail() {}

func (*RequestMessage_SetHeadSculptureAction) isRequestMessage_ActionDetail() {}

func (*RequestMessage_GetUserHeadImage) isRequestMessage_ActionDetail() {}

type UintkeyUintvalue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []uint64 `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *UintkeyUintvalue) Reset() {
	*x = UintkeyUintvalue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UintkeyUintvalue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UintkeyUintvalue) ProtoMessage() {}

func (x *UintkeyUintvalue) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UintkeyUintvalue.ProtoReflect.Descriptor instead.
func (*UintkeyUintvalue) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{10}
}

func (x *UintkeyUintvalue) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *UintkeyUintvalue) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type UintkeyStringvalue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *UintkeyStringvalue) Reset() {
	*x = UintkeyStringvalue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UintkeyStringvalue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UintkeyStringvalue) ProtoMessage() {}

func (x *UintkeyStringvalue) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UintkeyStringvalue.ProtoReflect.Descriptor instead.
func (*UintkeyStringvalue) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{11}
}

func (x *UintkeyStringvalue) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *UintkeyStringvalue) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SendMessageAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendData map[uint64]*UintkeyStringvalue `protobuf:"bytes,1,rep,name=send_data,json=sendData,proto3" json:"send_data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SendMessageAction) Reset() {
	*x = SendMessageAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageAction) ProtoMessage() {}

func (x *SendMessageAction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageAction.ProtoReflect.Descriptor instead.
func (*SendMessageAction) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{12}
}

func (x *SendMessageAction) GetSendData() map[uint64]*UintkeyStringvalue {
	if x != nil {
		return x.SendData
	}
	return nil
}

type SendMessageDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details []*SendMessageAction `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *SendMessageDetail) Reset() {
	*x = SendMessageDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageDetail) ProtoMessage() {}

func (x *SendMessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageDetail.ProtoReflect.Descriptor instead.
func (*SendMessageDetail) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{13}
}

func (x *SendMessageDetail) GetDetails() []*SendMessageAction {
	if x != nil {
		return x.Details
	}
	return nil
}

type SendVCardMessageDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail []*SendVCardMsgAction `protobuf:"bytes,1,rep,name=detail,proto3" json:"detail,omitempty"`
}

func (x *SendVCardMessageDetail) Reset() {
	*x = SendVCardMessageDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVCardMessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVCardMessageDetail) ProtoMessage() {}

func (x *SendVCardMessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVCardMessageDetail.ProtoReflect.Descriptor instead.
func (*SendVCardMessageDetail) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{14}
}

func (x *SendVCardMessageDetail) GetDetail() []*SendVCardMsgAction {
	if x != nil {
		return x.Detail
	}
	return nil
}

type QueryPreKeyBundleDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details []*UintkeyUintvalue `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *QueryPreKeyBundleDetail) Reset() {
	*x = QueryPreKeyBundleDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPreKeyBundleDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPreKeyBundleDetail) ProtoMessage() {}

func (x *QueryPreKeyBundleDetail) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPreKeyBundleDetail.ProtoReflect.Descriptor instead.
func (*QueryPreKeyBundleDetail) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{15}
}

func (x *QueryPreKeyBundleDetail) GetDetails() []*UintkeyUintvalue {
	if x != nil {
		return x.Details
	}
	return nil
}

type SetHeadSculptureDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail []*SetHeadSculptureAction `protobuf:"bytes,1,rep,name=detail,proto3" json:"detail,omitempty"`
}

func (x *SetHeadSculptureDetail) Reset() {
	*x = SetHeadSculptureDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetHeadSculptureDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeadSculptureDetail) ProtoMessage() {}

func (x *SetHeadSculptureDetail) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeadSculptureDetail.ProtoReflect.Descriptor instead.
func (*SetHeadSculptureDetail) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{16}
}

func (x *SetHeadSculptureDetail) GetDetail() []*SetHeadSculptureAction {
	if x != nil {
		return x.Detail
	}
	return nil
}

// 定义返回消息
type ResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionResult  ActionResult             `protobuf:"varint,1,opt,name=action_result,json=actionResult,proto3,enum=ActionResult" json:"action_result,omitempty"`                                                                                             // 动作的返回状态
	AccountStatus map[string]AccountStatus `protobuf:"bytes,2,rep,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=AccountStatus"` // 帐号的执行状态字典
	PongMessage   string                   `protobuf:"bytes,3,opt,name=pong_message,json=pongMessage,proto3" json:"pong_message,omitempty"`
	// Types that are assignable to CallbackInfo:
	//
	//	*ResponseMessage_LoginCallbacks
	//	*ResponseMessage_TextMsgCallbacks
	//	*ResponseMessage_ReadMsgCallbacks
	CallbackInfo isResponseMessage_CallbackInfo `protobuf_oneof:"callbackInfo"`
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{17}
}

func (x *ResponseMessage) GetActionResult() ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return ActionResult_ALL_SUCCESS
}

func (x *ResponseMessage) GetAccountStatus() map[string]AccountStatus {
	if x != nil {
		return x.AccountStatus
	}
	return nil
}

func (x *ResponseMessage) GetPongMessage() string {
	if x != nil {
		return x.PongMessage
	}
	return ""
}

func (m *ResponseMessage) GetCallbackInfo() isResponseMessage_CallbackInfo {
	if m != nil {
		return m.CallbackInfo
	}
	return nil
}

func (x *ResponseMessage) GetLoginCallbacks() *LoginCallbacks {
	if x, ok := x.GetCallbackInfo().(*ResponseMessage_LoginCallbacks); ok {
		return x.LoginCallbacks
	}
	return nil
}

func (x *ResponseMessage) GetTextMsgCallbacks() *TextMsgCallbacks {
	if x, ok := x.GetCallbackInfo().(*ResponseMessage_TextMsgCallbacks); ok {
		return x.TextMsgCallbacks
	}
	return nil
}

func (x *ResponseMessage) GetReadMsgCallbacks() *ReadMsgCallbacks {
	if x, ok := x.GetCallbackInfo().(*ResponseMessage_ReadMsgCallbacks); ok {
		return x.ReadMsgCallbacks
	}
	return nil
}

type isResponseMessage_CallbackInfo interface {
	isResponseMessage_CallbackInfo()
}

type ResponseMessage_LoginCallbacks struct {
	LoginCallbacks *LoginCallbacks `protobuf:"bytes,4,opt,name=login_callbacks,json=loginCallbacks,proto3,oneof"`
}

type ResponseMessage_TextMsgCallbacks struct {
	TextMsgCallbacks *TextMsgCallbacks `protobuf:"bytes,5,opt,name=text_msg_callbacks,json=textMsgCallbacks,proto3,oneof"`
}

type ResponseMessage_ReadMsgCallbacks struct {
	ReadMsgCallbacks *ReadMsgCallbacks `protobuf:"bytes,6,opt,name=read_msg_callbacks,json=readMsgCallbacks,proto3,oneof"`
}

func (*ResponseMessage_LoginCallbacks) isResponseMessage_CallbackInfo() {}

func (*ResponseMessage_TextMsgCallbacks) isResponseMessage_CallbackInfo() {}

func (*ResponseMessage_ReadMsgCallbacks) isResponseMessage_CallbackInfo() {}

type LoginCallbacks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*LoginCallback `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *LoginCallbacks) Reset() {
	*x = LoginCallbacks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginCallbacks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCallbacks) ProtoMessage() {}

func (x *LoginCallbacks) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCallbacks.ProtoReflect.Descriptor instead.
func (*LoginCallbacks) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{18}
}

func (x *LoginCallbacks) GetResults() []*LoginCallback {
	if x != nil {
		return x.Results
	}
	return nil
}

type LoginCallback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserJid     uint64        `protobuf:"varint,1,opt,name=userJid,proto3" json:"userJid,omitempty"`
	LoginStatus AccountStatus `protobuf:"varint,2,opt,name=loginStatus,proto3,enum=AccountStatus" json:"loginStatus,omitempty"`
	ProxyUrl    string        `protobuf:"bytes,3,opt,name=proxyUrl,proto3" json:"proxyUrl,omitempty"`
	Comment     string        `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *LoginCallback) Reset() {
	*x = LoginCallback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCallback) ProtoMessage() {}

func (x *LoginCallback) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCallback.ProtoReflect.Descriptor instead.
func (*LoginCallback) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{19}
}

func (x *LoginCallback) GetUserJid() uint64 {
	if x != nil {
		return x.UserJid
	}
	return 0
}

func (x *LoginCallback) GetLoginStatus() AccountStatus {
	if x != nil {
		return x.LoginStatus
	}
	return AccountStatus_SUCCESS
}

func (x *LoginCallback) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *LoginCallback) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type TextMsgCallbacks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*TextMsgCallback `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *TextMsgCallbacks) Reset() {
	*x = TextMsgCallbacks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextMsgCallbacks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMsgCallbacks) ProtoMessage() {}

func (x *TextMsgCallbacks) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMsgCallbacks.ProtoReflect.Descriptor instead.
func (*TextMsgCallbacks) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{20}
}

func (x *TextMsgCallbacks) GetResults() []*TextMsgCallback {
	if x != nil {
		return x.Results
	}
	return nil
}

type TextMsgCallback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   uint64 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`     //发送人
	Receiver uint64 `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"` //接收人
	SendText string `protobuf:"bytes,3,opt,name=sendText,proto3" json:"sendText,omitempty"`  //消息内容
	SendTime int64  `protobuf:"varint,4,opt,name=sendTime,proto3" json:"sendTime,omitempty"` //发送时间
	ReqId    string `protobuf:"bytes,5,opt,name=reqId,proto3" json:"reqId,omitempty"`        //请求id
	Read     bool   `protobuf:"varint,6,opt,name=read,proto3" json:"read,omitempty"`         //已读
}

func (x *TextMsgCallback) Reset() {
	*x = TextMsgCallback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextMsgCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMsgCallback) ProtoMessage() {}

func (x *TextMsgCallback) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMsgCallback.ProtoReflect.Descriptor instead.
func (*TextMsgCallback) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{21}
}

func (x *TextMsgCallback) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *TextMsgCallback) GetReceiver() uint64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *TextMsgCallback) GetSendText() string {
	if x != nil {
		return x.SendText
	}
	return ""
}

func (x *TextMsgCallback) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *TextMsgCallback) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *TextMsgCallback) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

type ReadMsgCallbacks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ReadMsgCallback `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ReadMsgCallbacks) Reset() {
	*x = ReadMsgCallbacks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMsgCallbacks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMsgCallbacks) ProtoMessage() {}

func (x *ReadMsgCallbacks) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMsgCallbacks.ProtoReflect.Descriptor instead.
func (*ReadMsgCallbacks) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{22}
}

func (x *ReadMsgCallbacks) GetResults() []*ReadMsgCallback {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadMsgCallback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId string `protobuf:"bytes,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
}

func (x *ReadMsgCallback) Reset() {
	*x = ReadMsgCallback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_arthas_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMsgCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMsgCallback) ProtoMessage() {}

func (x *ReadMsgCallback) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_arthas_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMsgCallback.ProtoReflect.Descriptor instead.
func (*ReadMsgCallback) Descriptor() ([]byte, []int) {
	return file_protobuf_arthas_proto_rawDescGZIP(), []int{23}
}

func (x *ReadMsgCallback) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

var File_protobuf_arthas_proto protoreflect.FileDescriptor

var file_protobuf_arthas_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x72, 0x74, 0x68, 0x61,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0c, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a,
	0x4c, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x29, 0x0a,
	0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0d,
	0x48, 0x65, 0x61, 0x64, 0x53, 0x63, 0x75, 0x6c, 0x70, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x57, 0x0a,
	0x16, 0x53, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x53, 0x63, 0x75, 0x6c, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x64, 0x53,
	0x63, 0x75, 0x6c, 0x70, 0x74, 0x72, 0x75, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x53, 0x63, 0x75, 0x6c, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x11, 0x48, 0x65, 0x61, 0x64, 0x53, 0x63, 0x75, 0x6c, 0x70, 0x74, 0x72,
	0x75, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0xbd, 0x02, 0x0a, 0x05, 0x56, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x64, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x50, 0x72, 0x6f, 0x64, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x46, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x46, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x72, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4f, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a,
	0x58, 0x57, 0x61, 0x42, 0x69, 0x7a, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x58, 0x57, 0x61, 0x42, 0x69, 0x7a, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x45, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x69, 0x76, 0x65,
	0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x69, 0x76, 0x65, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0xd1, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x56,
	0x43, 0x61, 0x72, 0x64, 0x4d, 0x73, 0x67, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a,
	0x0a, 0x56, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x56, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x73, 0x67,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x63, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x56, 0x63, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x1a, 0x44, 0x0a, 0x0e, 0x56, 0x63, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x56, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xff, 0x01, 0x0a, 0x07, 0x4b,
	0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x10,
	0x72, 0x65, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x22, 0x9b, 0x01, 0x0a,
	0x14, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4b,
	0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6b, 0x65, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x44, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4b, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf5, 0x04, 0x0a, 0x0e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a,
	0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x17, 0x73, 0x79,
	0x6e, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x79,
	0x6e, 0x63, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x14, 0x73, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4b, 0x65, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x19, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x6b, 0x65, 0x79, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x17, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x72, 0x65, 0x6b, 0x65, 0x79, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x43, 0x0a, 0x12, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x48, 0x00, 0x52, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0b, 0x70, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x12,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x76, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x56,
	0x43, 0x61, 0x72, 0x64, 0x4d, 0x73, 0x67, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x10, 0x73, 0x65, 0x6e, 0x64, 0x56, 0x63, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x54, 0x0a, 0x19, 0x73, 0x65, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x63,
	0x75, 0x6c, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x53, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x53, 0x63,
	0x75, 0x6c, 0x70, 0x74, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x16, 0x73, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x53, 0x63, 0x75, 0x6c, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x65,
	0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x10, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0x3c, 0x0a, 0x10, 0x55, 0x69, 0x6e, 0x74, 0x6b, 0x65, 0x79, 0x55, 0x69, 0x6e,
	0x74, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x3e, 0x0a, 0x12, 0x55, 0x69, 0x6e, 0x74, 0x6b, 0x65, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0xa4, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x50, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x6b, 0x65,
	0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2c, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x45, 0x0a, 0x16, 0x53, 0x65,
	0x6e, 0x64, 0x56, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x2b, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x56, 0x43, 0x61, 0x72, 0x64,
	0x4d, 0x73, 0x67, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x22, 0x46, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79,
	0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2b, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x55, 0x69, 0x6e, 0x74, 0x6b, 0x65, 0x79, 0x55, 0x69, 0x6e, 0x74, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x49, 0x0a, 0x16, 0x53, 0x65, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x53, 0x63, 0x75, 0x6c, 0x70, 0x74, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x2f, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x53, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x53, 0x63, 0x75,
	0x6c, 0x70, 0x74, 0x75, 0x72, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x22, 0xd8, 0x03, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4a, 0x0a, 0x0e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6e, 0x67,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x73, 0x48, 0x00, 0x52, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x41, 0x0a, 0x12, 0x74, 0x65, 0x78, 0x74, 0x5f,
	0x6d, 0x73, 0x67, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x48, 0x00, 0x52, 0x10, 0x74, 0x65, 0x78, 0x74, 0x4d, 0x73,
	0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x41, 0x0a, 0x12, 0x72, 0x65,
	0x61, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x73, 0x67,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x61,
	0x64, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x1a, 0x50, 0x0a,
	0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x0e, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x3a, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x73, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x0d,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x4a, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x4a, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x3e, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22,
	0xa7, 0x01, 0x0a, 0x0f, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64, 0x22, 0x3e, 0x0a, 0x10, 0x52, 0x65, 0x61,
	0x64, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x2a, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x65, 0x61,
	0x64, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71,
	0x49, 0x64, 0x2a, 0xe0, 0x01, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x47, 0x4f,
	0x55, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x47,
	0x52, 0x4f, 0x55, 0x50, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12, 0x14,
	0x0a, 0x10, 0x53, 0x59, 0x4e, 0x43, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4b,
	0x45, 0x59, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x45, 0x4b,
	0x45, 0x59, 0x42, 0x55, 0x4e, 0x44, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x59,
	0x4e, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x43, 0x54, 0x53, 0x10, 0x06, 0x12, 0x0d, 0x0a,
	0x09, 0x50, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12,
	0x53, 0x45, 0x4e, 0x44, 0x5f, 0x56, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x54, 0x5f, 0x48, 0x45, 0x41, 0x44,
	0x5f, 0x53, 0x43, 0x55, 0x4c, 0x50, 0x54, 0x55, 0x52, 0x45, 0x10, 0x09, 0x12, 0x17, 0x0a, 0x13,
	0x47, 0x45, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x5f, 0x49, 0x4d,
	0x41, 0x47, 0x45, 0x10, 0x0a, 0x2a, 0x5d, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x4c, 0x4c, 0x5f, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41,
	0x4c, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41,
	0x4c, 0x4c, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x4c, 0x4c,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f,
	0x4e, 0x47, 0x10, 0x04, 0x2a, 0x5e, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54,
	0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x04, 0x53, 0x45, 0x41, 0x4c,
	0x10, 0x93, 0x03, 0x12, 0x0f, 0x0a, 0x0a, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x10, 0x91, 0x03, 0x32, 0x36, 0x0a, 0x06, 0x41, 0x72, 0x74, 0x68, 0x61, 0x73, 0x12, 0x2c,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x40, 0x0a, 0x0c,
	0x41, 0x72, 0x74, 0x68, 0x61, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x30, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_arthas_proto_rawDescOnce sync.Once
	file_protobuf_arthas_proto_rawDescData = file_protobuf_arthas_proto_rawDesc
)

func file_protobuf_arthas_proto_rawDescGZIP() []byte {
	file_protobuf_arthas_proto_rawDescOnce.Do(func() {
		file_protobuf_arthas_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_arthas_proto_rawDescData)
	})
	return file_protobuf_arthas_proto_rawDescData
}

var file_protobuf_arthas_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protobuf_arthas_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_protobuf_arthas_proto_goTypes = []interface{}{
	(Action)(0),                     // 0: Action
	(ActionResult)(0),               // 1: ActionResult
	(AccountStatus)(0),              // 2: AccountStatus
	(*OrdinaryAction)(nil),          // 3: OrdinaryAction
	(*LoginDetail)(nil),             // 4: loginDetail
	(*GetUserHeadImageAction)(nil),  // 5: GetUserHeadImageAction
	(*HeadSculpture)(nil),           // 6: HeadSculpture
	(*SetHeadSculptureAction)(nil),  // 7: SetHeadSculptureAction
	(*VCard)(nil),                   // 8: VCard
	(*SendVCardMsgAction)(nil),      // 9: SendVCardMsgAction
	(*KeyData)(nil),                 // 10: KeyData
	(*SyncAccountKeyAction)(nil),    // 11: SyncAccountKeyAction
	(*RequestMessage)(nil),          // 12: RequestMessage
	(*UintkeyUintvalue)(nil),        // 13: UintkeyUintvalue
	(*UintkeyStringvalue)(nil),      // 14: UintkeyStringvalue
	(*SendMessageAction)(nil),       // 15: SendMessageAction
	(*SendMessageDetail)(nil),       // 16: SendMessageDetail
	(*SendVCardMessageDetail)(nil),  // 17: SendVCardMessageDetail
	(*QueryPreKeyBundleDetail)(nil), // 18: QueryPreKeyBundleDetail
	(*SetHeadSculptureDetail)(nil),  // 19: SetHeadSculptureDetail
	(*ResponseMessage)(nil),         // 20: ResponseMessage
	(*LoginCallbacks)(nil),          // 21: LoginCallbacks
	(*LoginCallback)(nil),           // 22: LoginCallback
	(*TextMsgCallbacks)(nil),        // 23: TextMsgCallbacks
	(*TextMsgCallback)(nil),         // 24: TextMsgCallback
	(*ReadMsgCallbacks)(nil),        // 25: ReadMsgCallbacks
	(*ReadMsgCallback)(nil),         // 26: ReadMsgCallback
	nil,                             // 27: OrdinaryAction.LoginDetailEntry
	nil,                             // 28: SendVCardMsgAction.VcardDataEntry
	nil,                             // 29: SyncAccountKeyAction.KeyDataEntry
	nil,                             // 30: SendMessageAction.SendDataEntry
	nil,                             // 31: ResponseMessage.AccountStatusEntry
}
var file_protobuf_arthas_proto_depIdxs = []int32{
	27, // 0: OrdinaryAction.login_detail:type_name -> OrdinaryAction.LoginDetailEntry
	6,  // 1: SetHeadSculptureAction.HeadSculptrue_data:type_name -> HeadSculpture
	28, // 2: SendVCardMsgAction.Vcard_data:type_name -> SendVCardMsgAction.VcardDataEntry
	29, // 3: SyncAccountKeyAction.key_data:type_name -> SyncAccountKeyAction.KeyDataEntry
	0,  // 4: RequestMessage.action:type_name -> Action
	3,  // 5: RequestMessage.ordinary_action:type_name -> OrdinaryAction
	11, // 6: RequestMessage.sync_account_key_action:type_name -> SyncAccountKeyAction
	18, // 7: RequestMessage.query_prekeybundle_detail:type_name -> QueryPreKeyBundleDetail
	16, // 8: RequestMessage.sendmessage_detail:type_name -> SendMessageDetail
	9,  // 9: RequestMessage.send_vcard_message:type_name -> SendVCardMsgAction
	7,  // 10: RequestMessage.set_head_sculpture_action:type_name -> SetHeadSculptureAction
	5,  // 11: RequestMessage.get_user_head_image:type_name -> GetUserHeadImageAction
	30, // 12: SendMessageAction.send_data:type_name -> SendMessageAction.SendDataEntry
	15, // 13: SendMessageDetail.details:type_name -> SendMessageAction
	9,  // 14: SendVCardMessageDetail.detail:type_name -> SendVCardMsgAction
	13, // 15: QueryPreKeyBundleDetail.details:type_name -> UintkeyUintvalue
	7,  // 16: SetHeadSculptureDetail.detail:type_name -> SetHeadSculptureAction
	1,  // 17: ResponseMessage.action_result:type_name -> ActionResult
	31, // 18: ResponseMessage.account_status:type_name -> ResponseMessage.AccountStatusEntry
	21, // 19: ResponseMessage.login_callbacks:type_name -> LoginCallbacks
	23, // 20: ResponseMessage.text_msg_callbacks:type_name -> TextMsgCallbacks
	25, // 21: ResponseMessage.read_msg_callbacks:type_name -> ReadMsgCallbacks
	22, // 22: LoginCallbacks.results:type_name -> LoginCallback
	2,  // 23: LoginCallback.loginStatus:type_name -> AccountStatus
	24, // 24: TextMsgCallbacks.results:type_name -> TextMsgCallback
	26, // 25: ReadMsgCallbacks.results:type_name -> ReadMsgCallback
	4,  // 26: OrdinaryAction.LoginDetailEntry.value:type_name -> loginDetail
	8,  // 27: SendVCardMsgAction.VcardDataEntry.value:type_name -> VCard
	10, // 28: SyncAccountKeyAction.KeyDataEntry.value:type_name -> KeyData
	14, // 29: SendMessageAction.SendDataEntry.value:type_name -> UintkeyStringvalue
	2,  // 30: ResponseMessage.AccountStatusEntry.value:type_name -> AccountStatus
	12, // 31: Arthas.connect:input_type -> RequestMessage
	12, // 32: ArthasStream.connect:input_type -> RequestMessage
	20, // 33: Arthas.connect:output_type -> ResponseMessage
	20, // 34: ArthasStream.connect:output_type -> ResponseMessage
	33, // [33:35] is the sub-list for method output_type
	31, // [31:33] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_protobuf_arthas_proto_init() }
func file_protobuf_arthas_proto_init() {
	if File_protobuf_arthas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_arthas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdinaryAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserHeadImageAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadSculpture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetHeadSculptureAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVCardMsgAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAccountKeyAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UintkeyUintvalue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UintkeyStringvalue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVCardMessageDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPreKeyBundleDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetHeadSculptureDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginCallbacks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginCallback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextMsgCallbacks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextMsgCallback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMsgCallbacks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_arthas_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMsgCallback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_arthas_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*RequestMessage_OrdinaryAction)(nil),
		(*RequestMessage_SyncAccountKeyAction)(nil),
		(*RequestMessage_QueryPrekeybundleDetail)(nil),
		(*RequestMessage_SendmessageDetail)(nil),
		(*RequestMessage_PingMessage)(nil),
		(*RequestMessage_SendVcardMessage)(nil),
		(*RequestMessage_SetHeadSculptureAction)(nil),
		(*RequestMessage_GetUserHeadImage)(nil),
	}
	file_protobuf_arthas_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*ResponseMessage_LoginCallbacks)(nil),
		(*ResponseMessage_TextMsgCallbacks)(nil),
		(*ResponseMessage_ReadMsgCallbacks)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_arthas_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobuf_arthas_proto_goTypes,
		DependencyIndexes: file_protobuf_arthas_proto_depIdxs,
		EnumInfos:         file_protobuf_arthas_proto_enumTypes,
		MessageInfos:      file_protobuf_arthas_proto_msgTypes,
	}.Build()
	File_protobuf_arthas_proto = out.File
	file_protobuf_arthas_proto_rawDesc = nil
	file_protobuf_arthas_proto_goTypes = nil
	file_protobuf_arthas_proto_depIdxs = nil
}
