export const country = [
        { value:"1", label: "Malaysia"}
]

export const province = {
    "1":[
        { value:"1", label:"Johor"},
        { value:"2", label: "Kedah"},
        { value:"3", label:"Kelantan"},
        { value:"4", label: "Malacca"},
        { value:"5", label: "Negeri Sembilan"},
        { value:"6", label: "Pahang"},
        { value:"7", label: "Perak"},
        { value:"8", label: "Perlis"},
        { value:"9", label: "Pulau Pinang"},
        { value:"10", label: "Sabah"},
        { value:"11", label: "Sarawak"},
        { value:"12", label: "Selangor"},
        { value:"13", label: "Terengganu"},
        { value: "14", label: "Wilayah Persekutuan"}
    ]
}

export const city = {
    "1": [
        { value:"1", label:"Johor Bahru"},
        { value:"2", label:"Tebrau"},
        { value:"3", label:"Pasir Gudang"},
        { value:"4", label:"Bukit Indah"},
        { value:"5", label:"Skudai"},
        { value:"6", label:"Kluang"},
        { value:"7", label:"Batu Pahat"},
        { value:"8", label:"Muar"},
        { value:"9", label:"Ulu Tiram"},
        { value:"10", label:"Senai"},
        { value:"11", label:"Segamat"},
        { value:"12", label:"Kulai"},
        { value:"13", label:"Kota Tinggi"},
        { value:"14", label:"Pontian Kechil"},
        { value:"15", label:"Tangkak"},
        { value:"16", label:"Bukit Bakri"},
        { value:"17", label:"Yong Peng"},
        { value:"18", label:"Pekan Nenas"},
        { value:"19", label:"Labis"},
        { value:"20", label:"Mersing"},
        { value:"21", label:"Simpang Renggam"},
        { value:"22", label:"Parit Raja"},
        { value:"23", label:"Kelapa Sawit"},
        { value:"24", label:"Buloh Kasap"},
        { value:"25", label:"Chaah"}
        ],
      "2": [
        { value:"26", label:"Sungai Petani"},
        { value:"27", label:"Alor Setar"},
        { value:"28", label:"Kulim"},
        { value:"29", label:"Jitra / Kubang Pasu"},
        { value:"30", label:"Baling"},
        { value:"31", label:"Pendang"},
        { value:"32", label:"Langkawi"},
        { value:"33", label:"Yan"},
        { value:"34", label:"Sik"},
        { value:"35", label:"Kuala Nerang"},
        { value:"36", label:"Pokok Sena"},
        { value:"37", label:"Bandar Baharu"}
      ],
      "3": [
        { value:"38", label:"Kota Bharu"},
        { value:"39", label:"Pangkal Kalong"},
        { value:"40", label:"Tanah Merah"},
        { value:"41", label:"Peringat"},
        { value:"42", label:"Wakaf Baru"},
        { value:"43", label:"Kadok"},
        { value:"44", label:"Pasir Mas"},
        { value:"45", label:"Gua Musang"},
        { value:"46", label: "Kuala Krai"},
        { value:"47", label:"Tumpat"}
      ],
      "4": [
        { value: "48", label:"Bandaraya Melaka"},
        { value: "49", label:"Bukit Baru"},
        { value: "50", label:"Ayer Keroh"},
        { value: "51", label:"Klebang"},
        { value: "52", label:"Masjid Tanah"},
        { value: "53", label:"Sungai Udang"},
        { value: "54", label:"Batu Berendam"},
        { value: "55", label:"Alor Gajah"},
        { value: "56", label:"Bukit Rambai"},
        { value:  "57", label:"Ayer Molek"},
        { value: "58", label:"Bemban"},
        { value: "59", label:"Kuala Sungai Baru"},
        { value: "60", label:"Pulau Sebang"},
        { value: "61", label:"Jasin"}
      ],
      "5": [
        { value: "62", label:"Seremban"},
        { value: "63", label:"Port Dickson"},
        { value: "64", label:"Nilai"},
        { value: "65", label:"Bahau"},
        { value: "66", label:"Tampin"},
        { value: "67", label:"Kuala Pilah"}
      ],
      "6": [
        { value: "68", label:"Kuantan"},
        { value: "69", label:"Temerloh"},
        { value: "70", label:"Bentong"},
        { value: "71", label:"Mentakab"},
        { value: "72", label:"Raub"},
        { value: "73", label:"Jerantut"},
        { value: "74", label:"Pekan"},
        { value: "75", label:"Kuala Lipis"},
        { value: "76", label:"Bandar Jengka"},
        { value: "77", label:"Bukit Tinggi"}
      ],
      "7": [
        { value:"78", label:"Ipoh"},
        { value: "79", label:"Taiping"},
        { value: "80", label:"Sitiawan"},
        { value:"81", label:"Simpang Empat"},
        { value:"82", label:"Teluk Intan"},
        { value:"83", label:"Batu Gajah"},
        { value: "84", label:"Lumut"},
        { value:"85", label:"Kampung Koh"},
        { value: "86", label:"Kuala Kangsar"},
        { value: "87", label:"Sungai Siput Utara"},
        { value: "88", label:"Tapah"},
        { value: "89", label:"Bidor"},
        { value: "90", label: "Parit Buntar"},
        { value: "91", label:"Ayer Tawar"},
        { value: "92", label:"Bagan Serai"},
        { value: "93", label:"Tanjung Malim"},
        { value: "94", label:"Lawan Kuda Baharu"},
        { value: "95", label:"Pantai Remis"},
        { value: "96", label:"Kampar"}
      ],
      "8": [
        { value: "97", label:"Kangar"},
        { value: "98", label:"Kuala Perlis"}
      ],
      "9": [
        { value: "99", label:"Bukit Mertajam"},
        { value: "100", label:"Georgetown"},
        { value: "101", label:"Sungai Ara"},
        { value: "102", label:"Gelugor"},
        { value: "103", label:"Ayer Itam"},
        { value: "104", label:"Butterworth"},
        { value: "105", label:"Perai"},
        { value: "106", label:"Nibong Tebal"},
        { value: "107", label:"Permatang Kucing"},
        { value: "108", label:"Tanjung Tokong"},
        { value: "109", label:"Kepala Batas"},
        { value: "110", label:"Tanjung Bungah"},
        { value: "111", label:"Juru"}
      ],
      "10": [
        { value: "112", label:"Kota Kinabalu"},
        { value: "113", label:"Sandakan"},
        { value: "114", label:"Tawau"},
        { value: "115", label:"Lahad Datu"},
        { value: "116", label:"Keningau"},
        { value: "117", label:"Putatan"},
        { value: "118", label:"Donggongon"},
        { value: "119", label:"Semporna"},
        { value: "120", label:"Kudat"},
        { value: "121", label:"Kunak"},
        { value: "122", label:"Papar"},
        { value: "123", label:"Ranau"},
        { value: "124", label:"Beaufort"},
        { value: "125", label:"Kinarut"},
        { value: "126", label:"Kota Belud"}
      ],
      "11": [
        { value: "127", label:"Kuching"},
        { value: "128", label:"Miri"},
        { value: "129", label:"Sibu"},
        { value: "130", label:"Bintulu"},
        { value: "131", label:"Limbang"},
        { value: "132", label:"Sarikei"},
        { value: "133", label:"Sri Aman"},
        { value: "132", label:"Kapit"},
        { value: "135", label:"Batu Delapan Bazaar"},
        { value: "136", label:"Kota Samarahan"}
      ],
      "12": [
        { value: "137", label:"Subang Jaya"},
        { value: "138", label:"Klang"},
        { value: "139", label:"Ampang Jaya"},
        { value: "140", label:"Shah Alam"},
        { value: "141", label:"Petaling Jaya"},
        { value: "142", label:"Cheras"},
        { value: "143", label:"Kajang"},
        { value: "144", label:"Selayang Baru"},
        { value: "145", label: "Rawang"},
        { value: "146", label: "Taman Greenwood"},
        { value: "147", label:"Semenyih"},
        { value: "148", label:"Banting"},
        { value: "149", label:"Balakong"},
        { value: "150", label:"Gombak Setia"},
        { value: "151", label:"Kuala Selangor"},
        { value: "152", label:"Serendah"},
        { value: "153", label:"Bukit Beruntung"},
        { value: "154", label: "Pengkalan Kundang"},
        { value: "155", label:"Jenjarom"},
        { value: "156", label:"Sungai Besar"},
        { value: "157", label: "Batu Arang"},
        { value: "158", label:"Tanjung Sepat"},
        { value: "159", label:"Kuang"},
        { value: "160", label:"Kuala Kubu Baharu"},
        { value: "161", label: "Batang Berjuntai"},
        { value: "162", label: "Bandar Baru Salak Tinggi"},
        { value: "163", label: "Sekinchan"},
        { value: "164", label:"Sabak"},
        { value: "165", label:  "Tanjung Karang"},
        { value: "166", label:  "Beranang"},
        { value: "167", label:  "Sungai Pelek"},
        { value: "168", label: "Sepang"}
      ],
      "13": [
        { value: "169", label:"Kuala Terengganu"},
        { value: "170", label:"Chukai"},
        { value: "171", label:"Dungun"},
        { value: "172", label:"Kerteh"},
        { value: "173", label:"Kuala Berang"},
        { value: "174", label:"Marang"},
        { value: "175", label:"Paka"},
        { value: "176", label:"Jerteh"}
      ],
      "14": [
        { value: "177", label:"Kuala Lumpur"},
        { value: "178", label:"Labuan"},
        { value: "179", label:"Putrajaya"}
      ]
    }