apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app/name: gratahistudio
  name: gratahistudio
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app/name: gratahistudio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app/name: gratahistudio
      namespace: arts-system
    spec:
      containers:
        - image: liuzhihu1-docker.pkg.coding.net/arts/arts/gratahistudio:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /home
              port: 4887
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          name: gratahistudio
          ports:
            - containerPort: 4887
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /home
              port: 4887
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources: {}
          volumeMounts:
            - mountPath: /app/config.yaml
              name: config
              subPath: config.yaml
          workingDir: /app
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: arts-image-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: grata-config
