// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalSysOrgPortsDao is internal type for wrapping internal DAO implements.
type internalSysOrgPortsDao = *internal.SysOrgPortsDao

// sysOrgPortsDao is the data access object for table sys_org_ports.
// You can define custom methods on it to extend its functionality as you wish.
type sysOrgPortsDao struct {
	internalSysOrgPortsDao
}

var (
	// SysOrgPorts is globally public accessible object for table sys_org_ports operations.
	SysOrgPorts = sysOrgPortsDao{
		internal.NewSysOrgPortsDao(),
	}
)

// Fill with you ideas below.
