// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalSysOrgDao is internal type for wrapping internal DAO implements.
type internalSysOrgDao = *internal.SysOrgDao

// sysOrgDao is the data access object for table sys_org.
// You can define custom methods on it to extend its functionality as you wish.
type sysOrgDao struct {
	internalSysOrgDao
}

var (
	// SysOrg is globally public accessible object for table sys_org operations.
	SysOrg = sysOrgDao{
		internal.NewSysOrgDao(),
	}
)

// Fill with you ideas below.
