// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalSysScriptDao is internal type for wrapping internal DAO implements.
type internalSysScriptDao = *internal.SysScriptDao

// sysScriptDao is the data access object for table sys_script.
// You can define custom methods on it to extend its functionality as you wish.
type sysScriptDao struct {
	internalSysScriptDao
}

var (
	// SysScript is globally public accessible object for table sys_script operations.
	SysScript = sysScriptDao{
		internal.NewSysScriptDao(),
	}
)

// Fill with you ideas below.
