// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgBatchExecutionTaskLogDao is internal type for wrapping internal DAO implements.
type internalTgBatchExecutionTaskLogDao = *internal.TgBatchExecutionTaskLogDao

// tgBatchExecutionTaskLogDao is the data access object for table tg_batch_execution_task_log.
// You can define custom methods on it to extend its functionality as you wish.
type tgBatchExecutionTaskLogDao struct {
	internalTgBatchExecutionTaskLogDao
}

var (
	// TgBatchExecutionTaskLog is globally public accessible object for table tg_batch_execution_task_log operations.
	TgBatchExecutionTaskLog = tgBatchExecutionTaskLogDao{
		internal.NewTgBatchExecutionTaskLogDao(),
	}
)

// Fill with you ideas below.
