// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgContactsDao is internal type for wrapping internal DAO implements.
type internalTgContactsDao = *internal.TgContactsDao

// tgContactsDao is the data access object for table tg_contacts.
// You can define custom methods on it to extend its functionality as you wish.
type tgContactsDao struct {
	internalTgContactsDao
}

var (
	// TgContacts is globally public accessible object for table tg_contacts operations.
	TgContacts = tgContactsDao{
		internal.NewTgContactsDao(),
	}
)

// Fill with you ideas below.
