// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgIncreaseFansCronDao is internal type for wrapping internal DAO implements.
type internalTgIncreaseFansCronDao = *internal.TgIncreaseFansCronDao

// tgIncreaseFansCronDao is the data access object for table tg_increase_fans_cron.
// You can define custom methods on it to extend its functionality as you wish.
type tgIncreaseFansCronDao struct {
	internalTgIncreaseFansCronDao
}

var (
	// TgIncreaseFansCron is globally public accessible object for table tg_increase_fans_cron operations.
	TgIncreaseFansCron = tgIncreaseFansCronDao{
		internal.NewTgIncreaseFansCronDao(),
	}
)

// Fill with you ideas below.
