// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgKeepTaskDao is internal type for wrapping internal DAO implements.
type internalTgKeepTaskDao = *internal.TgKeepTaskDao

// tgKeepTaskDao is the data access object for table tg_keep_task.
// You can define custom methods on it to extend its functionality as you wish.
type tgKeepTaskDao struct {
	internalTgKeepTaskDao
}

var (
	// TgKeepTask is globally public accessible object for table tg_keep_task operations.
	TgKeepTask = tgKeepTaskDao{
		internal.NewTgKeepTaskDao(),
	}
)

// Fill with you ideas below.
