// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgUserPortsDao is internal type for wrapping internal DAO implements.
type internalTgUserPortsDao = *internal.TgUserPortsDao

// tgUserPortsDao is the data access object for table tg_user_ports.
// You can define custom methods on it to extend its functionality as you wish.
type tgUserPortsDao struct {
	internalTgUserPortsDao
}

var (
	// TgUserPorts is globally public accessible object for table tg_user_ports operations.
	TgUserPorts = tgUserPortsDao{
		internal.NewTgUserPortsDao(),
	}
)

// Fill with you ideas below.
