// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgUserMemberDao is internal type for wrapping internal DAO implements.
type internalTgUserMemberDao = *internal.TgUserMemberDao

// tgUserMemberDao is the data access object for table tg_user_member.
// You can define custom methods on it to extend its functionality as you wish.
type tgUserMemberDao struct {
	internalTgUserMemberDao
}

var (
	// TgUserMember is globally public accessible object for table tg_user_member operations.
	TgUserMember = tgUserMemberDao{
		internal.NewTgUserMemberDao(),
	}
)

// Fill with you ideas below.
