// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgUserFoldersDao is internal type for wrapping internal DAO implements.
type internalTgUserFoldersDao = *internal.TgUserFoldersDao

// tgUserFoldersDao is the data access object for table tg_user_folders.
// You can define custom methods on it to extend its functionality as you wish.
type tgUserFoldersDao struct {
	internalTgUserFoldersDao
}

var (
	// TgUserFolders is globally public accessible object for table tg_user_folders operations.
	TgUserFolders = tgUserFoldersDao{
		internal.NewTgUserFoldersDao(),
	}
)

// Fill with you ideas below.
