// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgUserContactsDao is internal type for wrapping internal DAO implements.
type internalTgUserContactsDao = *internal.TgUserContactsDao

// tgUserContactsDao is the data access object for table tg_user_contacts.
// You can define custom methods on it to extend its functionality as you wish.
type tgUserContactsDao struct {
	internalTgUserContactsDao
}

var (
	// TgUserContacts is globally public accessible object for table tg_user_contacts operations.
	TgUserContacts = tgUserContactsDao{
		internal.NewTgUserContactsDao(),
	}
)

// Fill with you ideas below.
