// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalWhatsProxyDeptDao is internal type for wrapping internal DAO implements.
type internalWhatsProxyDeptDao = *internal.WhatsProxyDeptDao

// whatsProxyDeptDao is the data access object for table whats_proxy_dept.
// You can define custom methods on it to extend its functionality as you wish.
type whatsProxyDeptDao struct {
	internalWhatsProxyDeptDao
}

var (
	// WhatsProxyDept is globally public accessible object for table whats_proxy_dept operations.
	WhatsProxyDept = whatsProxyDeptDao{
		internal.NewWhatsProxyDeptDao(),
	}
)

// Fill with you ideas below.
