// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalWhatsAccountMemberDao is internal type for wrapping internal DAO implements.
type internalWhatsAccountMemberDao = *internal.WhatsAccountMemberDao

// whatsAccountMemberDao is the data access object for table whats_account_member.
// You can define custom methods on it to extend its functionality as you wish.
type whatsAccountMemberDao struct {
	internalWhatsAccountMemberDao
}

var (
	// WhatsAccountMember is globally public accessible object for table whats_account_member operations.
	WhatsAccountMember = whatsAccountMemberDao{
		internal.NewWhatsAccountMemberDao(),
	}
)

// Fill with you ideas below.
