// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalWhatsContactsDao is internal type for wrapping internal DAO implements.
type internalWhatsContactsDao = *internal.WhatsContactsDao

// whatsContactsDao is the data access object for table whats_contacts.
// You can define custom methods on it to extend its functionality as you wish.
type whatsContactsDao struct {
	internalWhatsContactsDao
}

var (
	// WhatsContacts is globally public accessible object for table whats_contacts operations.
	WhatsContacts = whatsContactsDao{
		internal.NewWhatsContactsDao(),
	}
)

// Fill with you ideas below.
