// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalWhatsProxyDao is internal type for wrapping internal DAO implements.
type internalWhatsProxyDao = *internal.WhatsProxyDao

// whatsProxyDao is the data access object for table whats_proxy.
// You can define custom methods on it to extend its functionality as you wish.
type whatsProxyDao struct {
	internalWhatsProxyDao
}

var (
	// WhatsProxy is globally public accessible object for table whats_proxy operations.
	WhatsProxy = whatsProxyDao{
		internal.NewWhatsProxyDao(),
	}
)

// Fill with you ideas below.
