// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalWhatsMsgHistoryDao is internal type for wrapping internal DAO implements.
type internalWhatsMsgHistoryDao = *internal.WhatsMsgHistoryDao

// whatsMsgHistoryDao is the data access object for table whats_msg_history.
// You can define custom methods on it to extend its functionality as you wish.
type whatsMsgHistoryDao struct {
	internalWhatsMsgHistoryDao
}

var (
	// WhatsMsgHistory is globally public accessible object for table whats_msg_history operations.
	WhatsMsgHistory = whatsMsgHistoryDao{
		internal.NewWhatsMsgHistoryDao(),
	}
)

// Fill with you ideas below.
