// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalWhatsAccountDao is internal type for wrapping internal DAO implements.
type internalWhatsAccountDao = *internal.WhatsAccountDao

// whatsAccountDao is the data access object for table whats_account.
// You can define custom methods on it to extend its functionality as you wish.
type whatsAccountDao struct {
	internalWhatsAccountDao
}

var (
	// WhatsAccount is globally public accessible object for table whats_account operations.
	WhatsAccount = whatsAccountDao{
		internal.NewWhatsAccountDao(),
	}
)

// Fill with you ideas below.
