name: Release Linux Version

on: [ push ]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: build
        run: |
          cd ./web 
          npm install
          npm run build 
          
          cp -rf ./dist/*  ../server/resource/public/
          
          cd ../server 
          
          CGO_ENABLED=0 go build -tags netgo -o ./temp/linux_amd64/grata main.go

      - name: Login to Coding
        uses: docker/login-action@v3
        with:
          registry: liuzhihu1-docker.pkg.coding.net
          username: vdpTODGnke
          password: 6a792aa8e716fafb358ff3008621a83920fbb896
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/manifest/docker/Dockerfile
          push: true
          tags: liuzhihu1-docker.pkg.coding.net/arts/arts/grata:latest
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: |
            apiVersion: v1
            kind: Config
            clusters:
            - name: "test"
              cluster:
                server: "https://34.124.217.133:442/k8s/clusters/c-b6nqz"
                certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQ\
                  VM2Z0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
                  kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
                  GNOTWpNdwpNakl6TURneE1qQTNXaGNOTXpNd01qSXdNRGd4TWpBM1dqQTdNUnd3R2dZRFZRUUtFe\
                  E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
                  1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRPSEFuMkZ0NHhCV\
                  WpBT0hoeXJSQUsxL3NYZ0ZzNHFGL1pLUGpHOGU5TAp5anoyMlNNdTM3Q2hzV0RKSTVUOFovMllNV\
                  kpNR1pma1BSbE9KWWxSYUdwam95TXdJVEFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
                  UgvQkFVd0F3RUIvekFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBZ09WbmZsTHgKY1VRc0tPL29kU\
                  1hmd0JuSlc2WFZLZWdBOG8xTTNGSlUvRXNDSVFDTFlLQlZPUytraHpQdjFqeVZOZlZZK0JQMQp2M\
                  1hvOUtLZit3cGNXdGhqWUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"


            users:
            - name: "test"
              user:
                token: "kubeconfig-user-vqxvk.c-b6nqz:p5stnwgdb2bc7ptqpkk82w44g9xtrv6smdljpjchf92n82blkrxzqc"


            contexts:
            - name: "test"
              context:
                user: "test"
                cluster: "test"

            current-context: "test"
      - uses: azure/k8s-bake@v2.4
        with:
          renderEngine: 'kustomize'
          kustomizationPath: './server/manifest/deploy/kustomize/overlays/test'
          kubectl-version: 'latest'