name: Release Linux Version

on: [ push ]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: build
        run: |
          cd ./web 
          npm install
          npm run build 
          
          cp -rf ./dist/*  ../server/resource/public/
          
          cd ../server 
          
          go build -o ./temp/linux_amd64/grata main.go

      # 登录到 阿里云镜像服务，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/manifest/docker/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/it00021hot/grata:latest