name: Release Linux Version

on: [ push ]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: build
        run: |
          cd ./web 
          npm install
          npm run build 
          
          cp -rf ./dist/*  ../server/resource/public/
          
          cd ../server 
          
          go build -tags netgo -o ./temp/linux_amd64/grata main.go

      - name: Login to Coding
        uses: docker/login-action@v3
        with:
          registry: liuzhihu1-docker.pkg.coding.net
          username: vdpTODGnke
          password: 6a792aa8e716fafb358ff3008621a83920fbb896
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/manifest/docker/Dockerfile
          push: true
          tags: liuzhihu1-docker.pkg.coding.net/arts/arts/grata:latest
